MyFirstWebServer333/MyFirstWebServer333/Controllers/VendorController.cs
using Microsoft.AspNetCore.Mvc;
using MyFirstWebServer333.Data;
using MyFirstWebServer333.Models.Entities;

namespace MyFirstWebServer333.Controllers;

public class VendorController : Controller
{

    private readonly ApplicationDbContext _context;

    /// <summary>
    /// Создает класс контроллер
    /// </summary>
    /// <param name="context">Соединение с БД</param>
    public VendorController(ApplicationDbContext context)
    {
        _context = context;
    }

    // GET
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(
        string name,
        string country,
        string email
    )
    {
        VendorModel newVendor = new VendorModel();
        newVendor.Name = name;
        newVendor.Country = country;
        newVendor.Email = email;
        _context.Add(newVendor);
        _context.SaveChangesAsync();
        ViewBag.vendor = newVendor;
        return View();
    }
}
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

MyFirstWebServer333/MyFirstWebServer333/Views/Vendor/Create.cshtml
<ul>
    <li>@ViewBag.vendor.Name</li>
    <li>@ViewBag.vendor.Country</li>
    <li>@ViewBag.vendor.Email</li>
</ul>

MyFirstWebServer333/MyFirstWebServer333/Views/Vendor/index.cshtml
<h1> Create Vendor</h1>

<div>
    <div>
        <h3 class="widget-heading">Create Vendor</h3>
        <form
            asp-controller="Vendor"
            asp-action="Create">
            <div class="mb-2">
                <input type="text"
                       class="form-control" name="name" placeholder="Enter vendor name">
            </div>
            <div class="mb-2">
                <input type="text"
                       class="form-control" name="country" placeholder="Enter vendor country">
            </div>
            <div class="mb-2">
                <input type="text"
                       class="form-control" name="email" placeholder="Enter vendor email">
            </div>
            <div class="mb-2">
                <input type="submit" value="Save">
            </div>
            
        </form>
    </div>
</div>